name: mqtt_client
description: A server and browser based MQTT client for Dart supporting normal, secure sockets and websockets.
version: 9.8.1
repository: https://github.com/shamblett/mqtt_client
homepage: https://github.com/shamblett/mqtt_client

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  typed_data: '^1.3.1'
  event_bus: '^2.0.0'
  path: '^1.8.2'
  crypto: '^3.0.2'
  meta: '^1.8.0'

dev_dependencies:
  test: '^1.23.1'
  lints: '^2.0.1'
  build_runner: '^2.3.3'
  build_test: '^2.1.6'
  build_web_compilers: '^3.2.7'
  http: '^0.13.5'
  sigv4: '^5.0.0'
  mocktail: '^0.3.0'

false_secrets:
  - /test/pem/self_signed.key
  - /test/pem/localhost.key
